<a href="https://colab.research.google.com/github/jade0520/DeepLearning_FromScratch/blob/master/reshape_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1차원-->다차원

In [18]:
import numpy as np

x = np.arange(60)
print(*x)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59


reshape(i,-1) 

i로 나눠서 행을 채운다.

In [19]:
y = x.reshape(2,-1)
print(*y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]


reshape(i,j,-1)
행을 채운 후, 행마다 j로 나눈다.

In [20]:
y = x.reshape(2,3,-1)
print(*y)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] [[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


reshape(i, j, k,-1)
j로 나눠진 것을 다시 k로 나눈다.

In [21]:
y = x.reshape(2,3,5,-1)
print(*y)



[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]] [[[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]]

 [[50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]]


#다차원->1차원

In [23]:
# 요순의 순서를 유지한다.
z = y.reshape(2,3,-1)
print(*z)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] [[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
